# Generated by Django 4.2.7 on 2026-08-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_habit_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notified",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее уведомление"
            ),
        ),
    ]
